import { Url } from "@/utils/brandedTypes"

import { type Species, SpeciesId } from "./Species"

const allPlants: Species[] = [
  {
    id: SpeciesId(1),
    scientificName: "Succisa pratensis",
    family: "Caprifoliaceae",
    commonNames: ["Devil's-bit Scabious", "Devil's-bit"],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.23w") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Succisa_pratensis") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/devils-bit-scabious") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_scabious.html#Devil's-bit%20Scabious"),
      },
    ],
    idTips: ["Flower heads rounded with equal sized [[floret]]s", "All leaves [[entire]]", "[[Corolla]] 4-lobed"],
  },
  {
    id: SpeciesId(2),
    scientificName: "Tanacetum vulgare",
    family: "Asteraceae",
    commonNames: ["Tansy"],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9b1") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Tanacetum_vulgare") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/tansy") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_yellowbutton.html#Common%20Tansy"),
      },
    ],
    idTips: [
      "The plant has bright yellow, button-like flower heads arranged in flat-topped clusters.",
      "The flower heads lack [[ray florets]] and consist only of tightly packed [[disc florets]].",
      "The leaves are deeply divided into many narrow, toothed segments.",
    ],
  },
  {
    id: SpeciesId(15),
    scientificName: "Tanacetum parthenium",
    family: "Asteraceae",
    commonNames: ["Feverfew"],
    links: [],
    idTips: [],
  },
  {
    id: SpeciesId(3),
    scientificName: "Knautia arvensis",
    family: "Caprifoliaceae",
    commonNames: ["Field Scabious"],
    links: [],
    idTips: [],
  },
  {
    id: SpeciesId(4),
    scientificName: "Scabiosa columbaria",
    family: "Caprifoliaceae",
    commonNames: ["Small Scabious"],
    links: [],
    idTips: [],
  },
  {
    id: SpeciesId(5),
    scientificName: "Hyacinthoides non-scripta",
    family: "Asparagaceae",
    commonNames: ["Bluebell"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.z9") }],
    idTips: [],
  },
  {
    id: SpeciesId(6),
    scientificName: "Campanula rotundifolia",
    family: "Campanulaceae",
    commonNames: ["Harebell"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.bys") }],
    idTips: [],
  },
  {
    id: SpeciesId(7),
    scientificName: "Cichorium intybus",
    family: "Asteraceae",
    commonNames: ["Chicory"],
    links: [],
    idTips: [],
  },
  {
    id: SpeciesId(8),
    scientificName: "Jasione montana",
    family: "Campanulaceae",
    commonNames: ["Sheep's-bit"],
    links: [],
    idTips: [],
  },
  {
    id: SpeciesId(9),
    scientificName: "Ranunculus acris",
    family: "Ranunculaceae",
    commonNames: ["Meadow Buttercup"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cfz") }],
    idTips: [],
  },
  {
    id: SpeciesId(10),
    scientificName: "Lotus corniculatus",
    family: "Fabaceae",
    commonNames: ["Bird's-foot Trefoil"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1e3") }],
    idTips: [],
  },
  {
    id: SpeciesId(11),
    scientificName: "Primula farinosa",
    family: "Primulaceae",
    commonNames: ["Bird's-eye Primrose"],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.94n") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Primula_farinosa") },
    ],
    idTips: [],
  },
  {
    id: SpeciesId(16),
    scientificName: "Primula veris",
    family: "Primulaceae",
    commonNames: ["Cowslip"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.94t") }],
    idTips: [],
  },
  {
    id: SpeciesId(12),
    scientificName: "Geranium robertianum",
    family: "Geraniaceae",
    commonNames: ["Herb-Robert", "Stinking Bob"],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8nb") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Geranium_robertianum") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_erodium.html#Common%20Herb-Robert"),
      },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/herb-robert") },
    ],
    idTips: [],
  },
  {
    id: SpeciesId(13),
    scientificName: "Geranium lucidum",
    family: "Geraniaceae",
    commonNames: ["Shining Crane's-bill"],
    links: [],
    idTips: [],
  },
  {
    id: SpeciesId(14),
    scientificName: "Bellis perennis",
    family: "Asteraceae",
    commonNames: ["Daisy"],
    links: [
      { name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xbs") },
      { name: "Wikipedia", url: Url("https://en.wikipedia.org/wiki/Bellis_perennis") },
      { name: "NatureSpot", url: Url("https://www.naturespot.org/species/daisy") },
      {
        name: "Flora of East Anglia",
        url: Url("http://webidguides.com/_templates/group_whitedaisies.html#Common%20Daisy"),
      },
    ],
    idTips: [],
  },
  {
    id: SpeciesId(17),
    scientificName: "Agrimonia eupatoria",
    family: "Rosaceae",
    commonNames: ["Agrimony"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.bwy") }],
    idTips: [],
  },
  {
    id: SpeciesId(18),
    scientificName: "Smyrnium olusatrum",
    family: "Apiaceae",
    commonNames: ["Alexanders"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.21r") }],
    idTips: [],
  },
  {
    id: SpeciesId(19),
    scientificName: "Alchemilla alpina",
    family: "Rosaceae",
    commonNames: ["Alpine Lady's-mantle"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.x8s") }],
    idTips: [],
  },
  {
    id: SpeciesId(20),
    scientificName: "Fraxinus excelsior",
    family: "Oleaceae",
    commonNames: ["Ash"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yxr") }],
    idTips: [],
  },
  {
    id: SpeciesId(21),
    scientificName: "Fagus sylvatica",
    family: "Fagaceae",
    commonNames: ["Beech"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fa2") }],
    idTips: [],
  },
  {
    id: SpeciesId(22),
    scientificName: "Erica cinerea",
    family: "Ericaceae",
    commonNames: ["Bell Heather"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.537") }],
    idTips: [],
  },
  {
    id: SpeciesId(23),
    scientificName: "Vaccinium myrtillus",
    family: "Ericaceae",
    commonNames: ["Bilberry"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w50") }],
    idTips: [],
  },
  {
    id: SpeciesId(24),
    scientificName: "Narthecium ossifragum",
    family: "Nartheciaceae",
    commonNames: ["Bog Asphodel"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.90z") }],
    idTips: [],
  },
  {
    id: SpeciesId(25),
    scientificName: "Menyanthes trifoliata",
    family: "Menyanthaceae",
    commonNames: ["Bogbean"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1g4") }],
    idTips: [],
  },
  {
    id: SpeciesId(26),
    scientificName: "Pteridium aquilinum",
    family: "Dennstaedtiaceae",
    commonNames: ["Bracken"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.y9r") }],
    idTips: [],
  },
  {
    id: SpeciesId(27),
    scientificName: "Rubus fruticosus",
    family: "Rosaceae",
    commonNames: ["Bramble"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vzf") }],
    idTips: [],
  },
  {
    id: SpeciesId(28),
    scientificName: "Sparganium erectum",
    family: "Typhaceae",
    commonNames: ["Branched Bur-reed"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cxx") }],
    idTips: [],
  },
  {
    id: SpeciesId(29),
    scientificName: "Veronica beccabunga",
    family: "Plantaginaceae",
    commonNames: ["Brooklime"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p9t") }],
    idTips: [],
  },
  {
    id: SpeciesId(30),
    scientificName: "Cytisus scoparius",
    family: "Fabaceae",
    commonNames: ["Broom"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.m2y") }],
    idTips: [],
  },
  {
    id: SpeciesId(31),
    scientificName: "Plantago coronopus",
    family: "Plantaginaceae",
    commonNames: ["Buck's-horn Plantain"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p05") }],
    idTips: [],
  },
  {
    id: SpeciesId(32),
    scientificName: "Buddleja davidii",
    family: "Scrophulariaceae",
    commonNames: ["Butterfly-bush"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xy") }],
    idTips: [],
  },
  {
    id: SpeciesId(33),
    scientificName: "Ajuga reptans",
    family: "Lamiaceae",
    commonNames: ["Bugle"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ez4") }],
    idTips: [],
  },
  {
    id: SpeciesId(34),
    scientificName: "Ranunculus bulbosus",
    family: "Ranunculaceae",
    commonNames: ["Bulbous Buttercup"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5w9") }],
    idTips: [],
  },
  {
    id: SpeciesId(35),
    scientificName: "Petasites hybridus",
    family: "Asteraceae",
    commonNames: ["Butterbur"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yzx") }],
    idTips: [],
  },
  {
    id: SpeciesId(36),
    scientificName: "Galium aparine",
    family: "Rubiaceae",
    commonNames: ["Cleavers"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ymq") }],
    idTips: [],
  },
  {
    id: SpeciesId(37),
    scientificName: "Tussilago farfara",
    family: "Asteraceae",
    commonNames: ["Colt's-foot"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.258") }],
    idTips: [],
  },
  {
    id: SpeciesId(38),
    scientificName: "Pinguicula vulgaris",
    family: "Lentibulariaceae",
    commonNames: ["Common Butterwort"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p02") }],
    idTips: [],
  },
  {
    id: SpeciesId(39),
    scientificName: "Stellaria media",
    family: "Caryophyllaceae",
    commonNames: ["Common Chickweed"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w2r") }],
    idTips: [],
  },
  {
    id: SpeciesId(40),
    scientificName: "Melampyrum pratense",
    family: "Orobanchaceae",
    commonNames: ["Common Cow-wheat"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yrz") }],
    idTips: [],
  },
  {
    id: SpeciesId(41),
    scientificName: "Polygala vulgaris",
    family: "Polygalaceae",
    commonNames: ["Common Milkwort"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.93r") }],
    idTips: [],
  },
  {
    id: SpeciesId(42),
    scientificName: "Urtica dioica",
    family: "Urticaceae",
    commonNames: ["Common Nettle"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9c0") }],
    idTips: [],
  },
  {
    id: SpeciesId(43),
    scientificName: "Papaver rhoeas",
    family: "Papaveraceae",
    commonNames: ["Common Poppy"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yzc") }],
    idTips: [],
  },
  {
    id: SpeciesId(44),
    scientificName: "Alisma plantago-aquatica",
    family: "Alismataceae",
    commonNames: ["Water-plantain"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.4ms") }],
    idTips: [],
  },
  {
    id: SpeciesId(45),
    scientificName: "Anthriscus sylvestris",
    family: "Apiaceae",
    commonNames: ["Cow Parsley"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.v7e") }],
    idTips: [],
  },
  {
    id: SpeciesId(46),
    scientificName: "Vaccinium vitis-idaea",
    family: "Ericaceae",
    commonNames: ["Cowberry"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.26d") }],
    idTips: [],
  },
  {
    id: SpeciesId(47),
    scientificName: "Ranunculus repens",
    family: "Ranunculaceae",
    commonNames: ["Creeping Buttercup"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vt4") }],
    idTips: [],
  },
  {
    id: SpeciesId(48),
    scientificName: "Erica tetralix",
    family: "Ericaceae",
    commonNames: ["Cross-leaved Heath"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c00") }],
    idTips: [],
  },
  {
    id: SpeciesId(49),
    scientificName: "Empetrum nigrum",
    family: "Ericaceae",
    commonNames: ["Crowberry"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.veg") }],
    idTips: [],
  },
  {
    id: SpeciesId(50),
    scientificName: "Digitalis purpurea",
    family: "Plantaginaceae",
    commonNames: ["Foxglove"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ywh") }],
    idTips: [],
  },
  {
    id: SpeciesId(51),
    scientificName: "Lycopus europaeus",
    family: "Lamiaceae",
    commonNames: ["Gypsywort"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c87") }],
    idTips: [],
  },
  {
    id: SpeciesId(52),
    scientificName: "Ulex europaeus",
    family: "Fabaceae",
    commonNames: ["Gorse"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p9b") }],
    idTips: [],
  },
  {
    id: SpeciesId(53),
    scientificName: "Epilobium hirsutum",
    family: "Onagraceae",
    commonNames: ["Great Willowherb"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vep") }],
    idTips: [],
  },
  {
    id: SpeciesId(54),
    scientificName: "Plantago major",
    family: "Plantaginaceae",
    commonNames: ["Greater Plantain"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p08") }],
    idTips: [],
  },
  {
    id: SpeciesId(55),
    scientificName: "Asplenium scolopendrium",
    family: "Aspleniaceae",
    commonNames: ["Hart's-tongue"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y7dfc") }],
    idTips: [],
  },
  {
    id: SpeciesId(56),
    scientificName: "Crataegus monogyna",
    family: "Rosaceae",
    commonNames: ["Hawthorn"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f6c") }],
    idTips: [],
  },
  {
    id: SpeciesId(57),
    scientificName: "Calluna vulgaris",
    family: "Ericaceae",
    commonNames: ["Heather"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yea") }],
    idTips: [],
  },
  {
    id: SpeciesId(58),
    scientificName: "Stachys sylvatica",
    family: "Lamiaceae",
    commonNames: ["Hedge Woundwort"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.231") }],
    idTips: [],
  },
  {
    id: SpeciesId(59),
    scientificName: "Conium maculatum",
    family: "Apiaceae",
    commonNames: ["Hemlock"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.brm") }],
    idTips: [],
  },
  {
    id: SpeciesId(60),
    scientificName: "Eupatorium cannabinum",
    family: "Asteraceae",
    commonNames: ["Hemp-agrimony"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.xwb") }],
    idTips: [],
  },
  {
    id: SpeciesId(61),
    scientificName: "Ilex aquifolium",
    family: "Aquifoliaceae",
    commonNames: ["Holly"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.yp2") }],
    idTips: [],
  },
  {
    id: SpeciesId(62),
    scientificName: "Impatiens glandulifera",
    family: "Balsaminaceae",
    commonNames: ["Himalayan Balsam"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.18x") }],
    idTips: [],
  },
  {
    id: SpeciesId(63),
    scientificName: "Hedera helix",
    family: "Araliaceae",
    commonNames: ["Common & Atlantic Ivy"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.95p1tn") }],
    idTips: [],
  },
  {
    id: SpeciesId(64),
    scientificName: "Reynoutria japonica",
    family: "Polygonaceae",
    commonNames: ["Japanese Knotweed"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.7mm4kb") }],
    idTips: [],
  },
  {
    id: SpeciesId(65),
    scientificName: "Ficaria verna",
    family: "Ranunculaceae",
    commonNames: ["Lesser Celandine"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y9637") }],
    idTips: [],
  },
  {
    id: SpeciesId(66),
    scientificName: "Papaver dubium",
    family: "Papaveraceae",
    commonNames: ["Long-headed Poppy"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.3ep") }],
    idTips: [],
  },
  {
    id: SpeciesId(67),
    scientificName: "Arum maculatum",
    family: "Araceae",
    commonNames: ["Lords-and-Ladies"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ycr") }],
    idTips: [],
  },
  {
    id: SpeciesId(68),
    scientificName: "Comarum palustre",
    family: "Rosaceae",
    commonNames: ["Marsh Cinquefoil"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.6y8hka") }],
    idTips: [],
  },
  {
    id: SpeciesId(69),
    scientificName: "Pedicularis palustris",
    family: "Orobanchaceae",
    commonNames: ["Marsh Lousewort"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.ccc") }],
    idTips: [],
  },
  {
    id: SpeciesId(70),
    scientificName: "Cirsium palustre",
    family: "Asteraceae",
    commonNames: ["Marsh Thistle"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8hn") }],
    idTips: [],
  },
  {
    id: SpeciesId(71),
    scientificName: "Viola palustris",
    family: "Violaceae",
    commonNames: ["Marsh Violet"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.m7w") }],
    idTips: [],
  },
  {
    id: SpeciesId(72),
    scientificName: "Caltha palustris",
    family: "Ranunculaceae",
    commonNames: ["Marsh-marigold"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f36") }],
    idTips: [],
  },
  {
    id: SpeciesId(73),
    scientificName: "Geranium pratense",
    family: "Geraniaceae",
    commonNames: ["Meadow Crane's-bill"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vvv") }],
    idTips: [],
  },
  {
    id: SpeciesId(74),
    scientificName: "Filipendula ulmaria",
    family: "Rosaceae",
    commonNames: ["Meadowsweet"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.54r") }],
    idTips: [],
  },
  {
    id: SpeciesId(75),
    scientificName: "Umbilicus rupestris",
    family: "Crassulaceae",
    commonNames: ["Navelwort"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.267") }],
    idTips: [],
  },
  {
    id: SpeciesId(76),
    scientificName: "Chrysosplenium oppositifolium",
    family: "Saxifragaceae",
    commonNames: ["Opposite-leaved Golden-saxifrage"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f5g") }],
    idTips: [],
  },
  {
    id: SpeciesId(77),
    scientificName: "Leucanthemum vulgare",
    family: "Asteraceae",
    commonNames: ["Oxeye Daisy"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.q4") }],
    idTips: [],
  },
  {
    id: SpeciesId(78),
    scientificName: "Primula vulgaris",
    family: "Primulaceae",
    commonNames: ["Primrose"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5vd") }],
    idTips: [],
  },
  {
    id: SpeciesId(79),
    scientificName: "Lythrum salicaria",
    family: "Lythraceae",
    commonNames: ["Purple-loosestrife"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vmn") }],
    idTips: [],
  },
  {
    id: SpeciesId(80),
    scientificName: "Allium ursinum",
    family: "Amaryllidaceae",
    commonNames: ["Ramsons"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8a0") }],
    idTips: [],
  },
  {
    id: SpeciesId(81),
    scientificName: "Silene dioica",
    family: "Caryophyllaceae",
    commonNames: ["Red Campion"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vn4") }],
    idTips: [],
  },
  {
    id: SpeciesId(82),
    scientificName: "Trifolium pratense",
    family: "Fabaceae",
    commonNames: ["Red Clover"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cna") }],
    idTips: [],
  },
  {
    id: SpeciesId(83),
    scientificName: "Lamium purpureum",
    family: "Lamiaceae",
    commonNames: ["Red Dead-nettle"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.c66") }],
    idTips: [],
  },
  {
    id: SpeciesId(84),
    scientificName: "Typha latifolia",
    family: "Typhaceae",
    commonNames: ["Bulrush"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.9bp") }],
    idTips: [],
  },
  {
    id: SpeciesId(85),
    scientificName: "Plantago lanceolata",
    family: "Plantaginaceae",
    commonNames: ["Ribwort Plantain"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1xk") }],
    idTips: [],
  },
  {
    id: SpeciesId(86),
    scientificName: "Sorbus aucuparia",
    family: "Rosaceae",
    commonNames: ["Rowan"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w2c") }],
    idTips: [],
  },
  {
    id: SpeciesId(87),
    scientificName: "Lysimachia arvensis",
    family: "Primulaceae",
    commonNames: ["Scarlet Pimpernel"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vek3vn") }],
    idTips: [],
  },
  {
    id: SpeciesId(88),
    scientificName: "Pinus sylvestris",
    family: "Pinaceae",
    commonNames: ["Scots Pine"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fwn") }],
    idTips: [],
  },
  {
    id: SpeciesId(89),
    scientificName: "Prunella vulgaris",
    family: "Lamiaceae",
    commonNames: ["Selfheal"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.p1p") }],
    idTips: [],
  },
  {
    id: SpeciesId(90),
    scientificName: "Rumex acetosella",
    family: "Polygonaceae",
    commonNames: ["Sheep's Sorrel"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vzv") }],
    idTips: [],
  },
  {
    id: SpeciesId(91),
    scientificName: "Potentilla anserina",
    family: "Rosaceae",
    commonNames: ["Silverweed"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.1n3") }],
    idTips: [],
  },
  {
    id: SpeciesId(92),
    scientificName: "Iris foetidissima",
    family: "Iridaceae",
    commonNames: ["Stinking Iris"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.59a") }],
    idTips: [],
  },
  {
    id: SpeciesId(93),
    scientificName: "Phragmites australis",
    family: "Poaceae",
    commonNames: ["Common Reed"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.fwh") }],
    idTips: [],
  },
  {
    id: SpeciesId(94),
    scientificName: "Dipsacus fullonum",
    family: "Caprifoliaceae",
    commonNames: ["Wild Teasel"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vdh") }],
    idTips: [],
  },
  {
    id: SpeciesId(95),
    scientificName: "Armeria maritima",
    family: "Plumbaginaceae",
    commonNames: ["Thrift"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8b8") }],
    idTips: [],
  },
  {
    id: SpeciesId(96),
    scientificName: "Potentilla erecta",
    family: "Rosaceae",
    commonNames: ["Tormentil"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5v7") }],
    idTips: [],
  },
  {
    id: SpeciesId(97),
    scientificName: "Clematis vitalba",
    family: "Ranunculaceae",
    commonNames: ["Traveller's-joy"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8hq") }],
    idTips: [],
  },
  {
    id: SpeciesId(98),
    scientificName: "Vicia cracca",
    family: "Fabaceae",
    commonNames: ["Tufted Vetch"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.5q2") }],
    idTips: [],
  },
  {
    id: SpeciesId(99),
    scientificName: "Scrophularia auriculata",
    family: "Scrophulariaceae",
    commonNames: ["Water Figwort"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.w1g") }],
    idTips: [],
  },
  {
    id: SpeciesId(100),
    scientificName: "Lamium album",
    family: "Lamiaceae",
    commonNames: ["White Dead-nettle"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.8rg") }],
    idTips: [],
  },
  {
    id: SpeciesId(101),
    scientificName: "Daucus carota",
    family: "Apiaceae",
    commonNames: ["Carrots"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.k7f") }],
    idTips: [],
  },
  {
    id: SpeciesId(102),
    scientificName: "Anemone nemorosa",
    family: "Ranunculaceae",
    commonNames: ["Wood Anemone"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.gt") }],
    idTips: [],
  },
  {
    id: SpeciesId(103),
    scientificName: "Oxalis acetosella",
    family: "Oxalidaceae",
    commonNames: ["Wood-sorrel"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.cba") }],
    idTips: [],
  },
  {
    id: SpeciesId(104),
    scientificName: "Galium odoratum",
    family: "Rubiaceae",
    commonNames: ["Woodruff"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.f1t") }],
    idTips: [],
  },
  {
    id: SpeciesId(105),
    scientificName: "Achillea millefolium",
    family: "Asteraceae",
    commonNames: ["Yarrow"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.88t") }],
    idTips: [],
  },
  {
    id: SpeciesId(106),
    scientificName: "Iris pseudacorus",
    family: "Iridaceae",
    commonNames: ["Yellow Iris"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.vwt") }],
    idTips: [],
  },
  {
    id: SpeciesId(107),
    scientificName: "Rhinanthus minor",
    family: "Orobanchaceae",
    commonNames: ["Yellow-rattle"],
    links: [{ name: "Plant Atlas", url: Url("https://plantatlas2020.org/atlas/2cd4p9h.966") }],
    idTips: [],
  },
]

export const findSpecies = (id: SpeciesId): Species | undefined => allPlants.find((s) => s.id === id)

export const getAllSpecies = (): Species[] => allPlants
