version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  dev:
    desc: Start development server
    cmds:
      - pnpm dev

  tsc:
    desc: Type check
    cmds:
      - pnpm tsc --noEmit

  lint:
    desc: Run ESLint
    cmds:
      - pnpm lint

  format:
    desc: Format code with Prettier
    cmds:
      - pnpm format

  format:check:
    desc: Check code formatting
    cmds:
      - pnpm format:check

  test:ct:install:
    desc: Install Playwright browsers
    cmds:
      - pnpm exec playwright install --with-deps chromium

  test:ct:
    desc: Run component tests
    cmds:
      - pnpm test:ct

  test:ct:ui:
    desc: Run component tests with UI
    cmds:
      - pnpm exec playwright test -c playwright-ct.config.ts --ui

  test:unit:
    desc: Run unit tests
    cmds:
      - pnpm test:unit

  build:
    desc: Build the project
    cmds:
      - pnpm build

  knip:
    desc: Find unused code
    cmds:
      - pnpm exec knip

  check:
    desc: Run all checks (tsc, lint, format, tests)
    cmds:
      - task: tsc
      - task: lint
      - task: format:check
      - task: test:unit
      - task: test:ct

  ngrok:
    desc: Expose local dev server via ngrok
    cmds:
      - ngrok http 5173
