version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  dev:
    desc: Start development server
    cmds:
      - pnpm dev

  tsc:
    desc: Type check
    cmds:
      - pnpm tsc --noEmit

  lint:
    desc: Run ESLint
    cmds:
      - pnpm lint

  format:
    desc: Format code with Prettier
    cmds:
      - pnpm format

  format:check:
    desc: Check code formatting
    cmds:
      - pnpm format:check

  test:ct:install:
    desc: Install Playwright browsers
    cmds:
      - pnpm exec playwright install --with-deps chromium

  test:ct:
    desc: Run component tests
    cmds:
      - pnpm test:ct

  test:ct:ui:
    desc: Run component tests with UI
    cmds:
      - pnpm exec playwright test -c playwright-ct.config.ts --ui

  test:unit:
    desc: Run unit tests
    cmds:
      - pnpm test:unit

  build:
    desc: Build the project
    cmds:
      - pnpm build

  analyze:
    desc: Build and analyze bundle size
    cmds:
      - ANALYZE=true pnpm build
      - echo Bundle analysis written to dist/stats.html

  knip:
    desc: Find unused code
    cmds:
      - pnpm exec knip

  check:
    desc: Run all checks (tsc, lint, format, tests)
    cmds:
      - task: tsc
      - task: lint
      - task: format:check
      - task: test:unit
      - task: test:ct

  ngrok:
    desc: Expose local dev server via ngrok
    cmds:
      - ngrok http 5173

  security:
    desc: Run trivy security scan
    cmds:
      - trivy fs --ignorefile .trivyignore.yaml --skip-version-check --include-dev-deps .

  secrets:
    desc: Scan for secrets with gitleaks
    cmds:
      - gitleaks detect --source . -v

  update-screenshots:
    aliases:
      - us
    desc: Trigger GitHub Actions workflow to update snapshots
    cmds:
      - gh workflow run update-snapshots.yml --ref main
      - sleep 2
      - GH_PAGER= gh run list --workflow=update-snapshots.yml --limit=1 --json url --jq '.[0].url'

  infra:install:
    desc: Install infrastructure dependencies
    dir: infra
    cmds:
      - pnpm install

  infra:tsc:
    desc: Type check infrastructure code
    dir: infra
    cmds:
      - pnpm tsc --noEmit

  infra:preview:
    desc: Preview infrastructure changes
    dir: infra
    cmds:
      - pulumi preview --stack prod

  infra:up:
    desc: Apply infrastructure changes
    dir: infra
    cmds:
      - pulumi up --stack prod
