/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ErrorTestRouteImport } from './routes/error-test'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewPuzzleIdRouteImport } from './routes/review/$puzzleId'
import { Route as ArchiveDateRouteImport } from './routes/archive/$date'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorTestRoute = ErrorTestRouteImport.update({
  id: '/error-test',
  path: '/error-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPuzzleIdRoute = ReviewPuzzleIdRouteImport.update({
  id: '/review/$puzzleId',
  path: '/review/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveDateRoute = ArchiveDateRouteImport.update({
  id: '/archive/$date',
  path: '/archive/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/error-test': typeof ErrorTestRoute
  '/history': typeof HistoryRoute
  '/archive/$date': typeof ArchiveDateRoute
  '/review/$puzzleId': typeof ReviewPuzzleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/error-test': typeof ErrorTestRoute
  '/history': typeof HistoryRoute
  '/archive/$date': typeof ArchiveDateRoute
  '/review/$puzzleId': typeof ReviewPuzzleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/error-test': typeof ErrorTestRoute
  '/history': typeof HistoryRoute
  '/archive/$date': typeof ArchiveDateRoute
  '/review/$puzzleId': typeof ReviewPuzzleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/daily'
    | '/error-test'
    | '/history'
    | '/archive/$date'
    | '/review/$puzzleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/daily'
    | '/error-test'
    | '/history'
    | '/archive/$date'
    | '/review/$puzzleId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/daily'
    | '/error-test'
    | '/history'
    | '/archive/$date'
    | '/review/$puzzleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DailyRoute: typeof DailyRoute
  ErrorTestRoute: typeof ErrorTestRoute
  HistoryRoute: typeof HistoryRoute
  ArchiveDateRoute: typeof ArchiveDateRoute
  ReviewPuzzleIdRoute: typeof ReviewPuzzleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-test': {
      id: '/error-test'
      path: '/error-test'
      fullPath: '/error-test'
      preLoaderRoute: typeof ErrorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$puzzleId': {
      id: '/review/$puzzleId'
      path: '/review/$puzzleId'
      fullPath: '/review/$puzzleId'
      preLoaderRoute: typeof ReviewPuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$date': {
      id: '/archive/$date'
      path: '/archive/$date'
      fullPath: '/archive/$date'
      preLoaderRoute: typeof ArchiveDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DailyRoute: DailyRoute,
  ErrorTestRoute: ErrorTestRoute,
  HistoryRoute: HistoryRoute,
  ArchiveDateRoute: ArchiveDateRoute,
  ReviewPuzzleIdRoute: ReviewPuzzleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
